apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: binding-dev
subjects:
- kind: ServiceAccount
  name: serviceaccount-dev
  namespace: okd-team
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: role-dev
