kind: Pod
apiVersion: v1
metadata:
  name: debugs-pod
  namespace: okd-team
spec:
  containers:
    - name: debug-pod-container
      image: busybox
      securityContext:
        privileged: true
        runAsUser: 0   
      volumeMounts:
      - mountPath: "/tmp"
        name: my-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: local-volume-pvc  
