kind: Pod
apiVersion: v1
metadata:
  name: debug-pod
  namespace: okd-team
spec:
  containers:
    - name: debug-pod-container
      image: registry.access.redhat.com/ubi8/ubi-init:latest
      volumeMounts:
      - mountPath: "/tmp"
        name: my-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: ${PVC_NAME}  
