apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-volume-pvc
  namespace: okd-team
  annotations:
    volumeType: local
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 2Gi
