apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipeline-pvc-dev
  namespace: okd-team
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  #storageClassName: standard
  storageClassName: ${STORAGE_CLASS}
