apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manual-pvc
  namespace: okd-team
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
