kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: build-cache-pvc-dev
  namespace: okd-team
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi
