apiVersion: triggers.tekton.dev/v1alpha1 
kind: TriggerBinding 
metadata:
  name: trigger-binding-dev
spec:
  params: 
  - name: repo-url
    value: $(body.url)
  - name: repo-name
    value: $(body.name)
  - name: bundle-version
    value: $(body.version)
  - name: base-image-registry
    value: $(body.imageregistry)
